### ISSUE TITLE
5.0.0 preparation plan

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.general#4507]
Once 4.8.0 has been released:

- [x] Create a PR which bumps the version of `main` to 5.0.0 and removes all deprecations. (#4516)
- [x] Deprecate norc of gem module. (#4517)
- [x] Look for Ansible 2.9 / ansible-base 2.10 specific code, create PR to remove it (#4548).
- [x] Create PR which remove symlinks, and update documentation on how to add new modules (#4562).
- [x] Add comments to existing new module PRs so they will be updated accordingly.
- [x] Improve CI coverage (#4563).
- [x] ~~Migrate SAP modules (#4149).~~

**Comment by felixfontein** [comment]
Potentially release 5.0.0-a1 alpha version?

**Comment by ansibullbot** [comment]
@felixfontein: Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.

Here are the items we could not find in your description:
- component name

Please set the description of this issue with an appropriate template from:
https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by felixfontein** [comment]
bot_skip

**Comment by felixfontein** [comment]
5.0.0 has been released a week ago. Time to close this :)
